[package]
name = "rhk"
version = "0.1.0"
authors = ["Alexander Bethel <abethel@cs.nmt.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
